os: Visual Studio 2015

version: "{build}-{branch}"

configuration: Release

environment:
  github_auth_token:
    secure: V1GojGQfrAiQtUWtNNXfm3samiH+1yNF5UYhkn8B8mbif20IGTGWNlBS9E4S0SUC
  bintray_auth_token:
    secure: fBQJmUDK/EgEUWjjbo6bWcitczeFTJZT4OZ3ZZ4FoUT6soBsTWPQJnr8YEVMFhGP

install:
  - ps: (New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/WrinklyNinja/ci-scripts/1.2.0/delete_old_bintray_versions.py', "$env:APPVEYOR_BUILD_FOLDER\delete_old_bintray_versions.py")

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: mkdir build
  - cd build
  - cmake .. -G "Visual Studio 14 2015"

build:
  verbosity: minimal
  project: '$(APPVEYOR_BUILD_FOLDER)\build\metadata-validator.sln'

after_test:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - cpack
  - ps: $env:GIT_DESCRIBE = ((git describe --tags --long --always --abbrev=7) | Out-String) -replace "`n|`r", ""

artifacts:
  - path: build\package\metadata-validator-$(GIT_DESCRIBE)_$(APPVEYOR_REPO_BRANCH)-win32.7z
    name: metadata-validator

deploy:
  - provider: BinTray
    username: wrinklyninja
    api_key:
      secure: fBQJmUDK/EgEUWjjbo6bWcitczeFTJZT4OZ3ZZ4FoUT6soBsTWPQJnr8YEVMFhGP
    subject: loot
    repo: snapshots
    package: metadata-validator
    version: $(GIT_DESCRIBE)_$(APPVEYOR_REPO_BRANCH)
    publish: true
    artifact: metadata-validator

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: LOOT Metadata Validator v$(APPVEYOR_REPO_TAG_NAME)
    description: |
      Windows users should download the file with the `7z` file extension. It requires Windows 7 or later and the [MSVC 2015 x86 redistributable](https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe), and [7-Zip](http://www.7-zip.org/) to extract the archive.

      The `metadata-validator.tar.xz` file contains a Linux binary.
    auth_token:
      secure: V1GojGQfrAiQtUWtNNXfm3samiH+1yNF5UYhkn8B8mbif20IGTGWNlBS9E4S0SUC
    artifact: metadata-validator
    draft: false
    force_update: true
    on:
      appveyor_repo_tag: true

on_success:
  - ps: |
      if ($env:bintray_auth_token) {
        python "$env:APPVEYOR_BUILD_FOLDER\delete_old_bintray_versions.py" -o loot -g loot -u loot -b snapshots -p metadata-validator -t $env:bintray_auth_token -a $env:github_auth_token -n 30
      }
