os: Visual Studio 2017

version: "{build}-{branch}"

configuration: Release

environment:
  github_auth_token:
    secure: yDqT5l/e5MntbW99V6+MHlfFgNv+UIogFfeyUVqtFk5lFRB/dAraLLwKCLl6y+DH
  bintray_auth_token:
    secure: PgsEA6TjHVf718zMnK7J/fT1hUAVNKBeWhpYgYaeCyeZk37VT4Ics6j7+B7ElLEr

install:
  - ps: (New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/WrinklyNinja/ci-scripts/2.0.0/delete_old_bintray_versions.py', "$env:APPVEYOR_BUILD_FOLDER\delete_old_bintray_versions.py")

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: mkdir build
  - cd build
  - cmake .. -G "Visual Studio 15 2017"

build:
  verbosity: minimal
  project: '$(APPVEYOR_BUILD_FOLDER)\build\metadata-validator.sln'

after_test:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - cpack
  - ps: $env:GIT_DESCRIBE = ((git describe --tags --long --always --abbrev=7) | Out-String) -replace "`n|`r", ""

artifacts:
  - path: build\package\metadata-validator-$(GIT_DESCRIBE)_$(APPVEYOR_REPO_BRANCH)-win32.7z
    name: metadata-validator

deploy:
  - provider: BinTray
    username: wrinklyninja
    api_key:
      secure: PgsEA6TjHVf718zMnK7J/fT1hUAVNKBeWhpYgYaeCyeZk37VT4Ics6j7+B7ElLEr
    subject: loot
    repo: snapshots
    package: metadata-validator
    version: $(GIT_DESCRIBE)_$(APPVEYOR_REPO_BRANCH)
    publish: true
    artifact: metadata-validator

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: LOOT Metadata Validator v$(APPVEYOR_REPO_TAG_NAME)
    description: |
      Windows users should download the file with the `7z` file extension. It requires Windows 7 or later and the [MSVC 2017 x86 redistributable](https://download.visualstudio.microsoft.com/download/pr/749aa419-f9e4-4578-a417-a43786af205e/d59197078cc425377be301faba7dd87a/vc_redist.x86.exe), and [7-Zip](http://www.7-zip.org/) to extract the archive.

      The `metadata-validator.tar.xz` file contains a Linux binary.
    auth_token:
      secure: yDqT5l/e5MntbW99V6+MHlfFgNv+UIogFfeyUVqtFk5lFRB/dAraLLwKCLl6y+DH
    artifact: metadata-validator
    draft: false
    force_update: true
    on:
      appveyor_repo_tag: true

on_success:
  - ps: |
      if ($env:bintray_auth_token) {
        python "$env:APPVEYOR_BUILD_FOLDER\delete_old_bintray_versions.py" -g loot/metadata-validator -b loot/snapshots/metadata-validator -u wrinklyninja -k $env:bintray_auth_token -t $env:github_auth_token -n 30
      }
