name: CI

on:
  push:
    # Don't run this workflow when a tag is pushed.
    branches:
      - '*'
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        runner-image:
          - windows-2025
          - ubuntu-24.04

    runs-on: ${{ matrix.runner-image }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Set LIBLOOT_REVISION
        shell: bash
        run: echo "LIBLOOT_REVISION=$(cargo metadata --format-version 1 | jq '.packages[] | select(.name == "libloot") | .source | split("#") | last')" >> $GITHUB_ENV

      - name: Set LMV_REVISION
        shell: bash
        run: echo "LMV_REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Run build
        run: cargo build --release

      - name: Get descriptive version
        id: get-version
        shell: bash
        run: |
          GIT_DESCRIBE=$(git describe --tags --long --abbrev=7)
          GIT_REF_SUFFIX=${GITHUB_REF#refs/*/}
          DESC_REF=${GIT_DESCRIBE}_${GIT_REF_SUFFIX}
          SAFE_DESC_REF=${DESC_REF//[\/<>\"|]/_}
          SAFE_GIT_REF_SUFFIX=${GIT_REF_SUFFIX//[\/<>\"|]/_}
          echo "version=$SAFE_DESC_REF" >> $GITHUB_OUTPUT
          echo "ref=$SAFE_GIT_REF_SUFFIX" >> $GITHUB_OUTPUT

      - name: Build archive
        id: build-archive
        shell: bash
        run: |
          python scripts/archive.py . "${{ steps.get-version.outputs.ref }}"

          VERSION="${{ steps.get-version.outputs.version }}"

          if [[ "${{ runner.os }}" == "Windows" ]]
          then
            echo "filename=metadata-validator-${VERSION}-win64.7z" >> $GITHUB_OUTPUT
          else
            echo "filename=metadata-validator-${VERSION}-Linux.tar.xz" >> $GITHUB_OUTPUT
          fi

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-archive.outputs.filename }}
          path: target/package/${{ steps.build-archive.outputs.filename }}
        if: github.event_name == 'push'
