name: Release

on:
  push:
    tags: '*'

env:
  MSVC_CONFIG: RelWithDebInfo

jobs:
  create_release:
    runs-on: ubuntu-24.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      git_tag: ${{ steps.get-git-tag.outputs.name }}

    steps:
      - name: Get Git tag
        id: get-git-tag
        run: echo "name=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-git-tag.outputs.name }}
          release_name: LOOT Metadata Validator v${{ steps.get-git-tag.outputs.name }}
          body: |
            Windows users should download the file with the `7z` file extension. It requires Windows 7 or later and the [MSVC 2022 x86 redistributable](https://aka.ms/vs/17/release/vc_redist.x86.exe), and [7-Zip](http://www.7-zip.org/) to extract the archive.

            The `metadata-validator.tar.xz` file contains a Linux binary.

  linux:
    runs-on: ubuntu-24.04
    needs: create_release

    env:
      LIBLOOT_VERSION: 0.28.0

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set libloot install path
        run: echo "LIBLOOT_INSTALL_PATH=${{ github.workspace }}/libloot-${{ env.LIBLOOT_VERSION }}-install" >> $GITHUB_ENV

      - name: libloot cache
        id: libloot-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.LIBLOOT_INSTALL_PATH }}
          key: ${{ runner.os }}-libloot-${{ env.LIBLOOT_VERSION }}

      - name: Get descriptive version
        id: get-version
        shell: bash
        run: |
          GIT_DESCRIBE=$(git describe --tags --long --abbrev=7)
          DESC_REF=${GIT_DESCRIBE}_${GITHUB_REF#refs/*/}
          SAFE_DESC_REF=${DESC_REF//[\/<>\"|]/_}
          echo "version=$SAFE_DESC_REF" >> $GITHUB_OUTPUT

      - name: Install APT package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-upgrade \
            libboost-dev \
            libicu-dev \
            libtbb-dev

      - name: Checkout libloot repository
        uses: actions/checkout@v4
        with:
          repository: loot/libloot
          ref: ${{ env.LIBLOOT_VERSION }}
          path: libloot-${{ env.LIBLOOT_VERSION }}
        if: steps.libloot-cache.outputs.cache-hit != 'true'

      - name: Download and build libloot
        run: |
          LIBLOOT_BUILD_DIR="libloot-$LIBLOOT_VERSION/cpp/build"

          cmake -DCMAKE_BUILD_TYPE=Release -DLIBLOOT_BUILD_TESTS=OFF -DLIBLOOT_INSTALL_DOCS=OFF -DCMAKE_INSTALL_PREFIX="$LIBLOOT_INSTALL_PATH" -B "$LIBLOOT_BUILD_DIR" -S "libloot-$LIBLOOT_VERSION/cpp"

          cmake --build "$LIBLOOT_BUILD_DIR" --target loot --config Release
          cmake --install "$LIBLOOT_BUILD_DIR" --config Release
        if: steps.libloot-cache.outputs.cache-hit != 'true'

      - name: Run CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{ env.LIBLOOT_INSTALL_PATH }}" -DCPACK_PACKAGE_VERSION="${{ steps.get-version.outputs.version }}"
          make all

      - name: Build archive
        id: build-archive
        shell: bash
        run: |
          cd build
          cpack
          VERSION="${{ steps.get-version.outputs.version }}"
          echo "filename=metadata-validator-${VERSION}-Linux.tar.xz" >> $GITHUB_OUTPUT

      - name: Upload Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: build/package/${{ steps.build-archive.outputs.filename }}
          asset_name: ${{ steps.build-archive.outputs.filename }}
          asset_content_type: application/octet-stream

  windows:
    runs-on: windows-2025
    needs: create_release

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get descriptive version
        id: get-version
        shell: bash
        run: |
          GIT_DESCRIBE=$(git describe --tags --long --abbrev=7)
          DESC_REF=${GIT_DESCRIBE}_${GITHUB_REF#refs/*/}
          SAFE_DESC_REF=${DESC_REF//[\/<>\"|]/_}
          echo "version=$SAFE_DESC_REF" >> $GITHUB_OUTPUT

      - name: Run CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCPACK_PACKAGE_VERSION="${{ steps.get-version.outputs.version }}"
          cmake --build . --config ${{ env.MSVC_CONFIG }}

      - name: Build archive
        id: build-archive
        shell: bash
        run: |
          cd build
          cpack -C ${{ env.MSVC_CONFIG }}
          VERSION="${{ steps.get-version.outputs.version }}"
          echo "filename=metadata-validator-${VERSION}-win64.7z" >> $GITHUB_OUTPUT

      - name: Upload Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: build/package/${{ steps.build-archive.outputs.filename }}
          asset_name: ${{ steps.build-archive.outputs.filename }}
          asset_content_type: application/x-7z-compressed
